// ═══════════════════════════════════════════════════════════════════
// GEO-DATA.JS — Données géographiques et géostratégiques mondiales
// Sources : CIA World Factbook, IISS Military Balance, IEA, USGS,
//           Nations Unies, Banque Mondiale, SIPRI, ONU-OCHA
// ═══════════════════════════════════════════════════════════════════

// ── MERS ET OCÉANS ─────────────────────────────────────────────────
const MERS = [
  { nom:"Océan Atlantique",     lon:-30,  lat:10,   type:"ocean",    superficie:"106 M km²" },
  { nom:"Océan Pacifique",      lon:-160, lat:10,   type:"ocean",    superficie:"165 M km²" },
  { nom:"Océan Indien",         lon:75,   lat:-20,  type:"ocean",    superficie:"70 M km²" },
  { nom:"Océan Arctique",       lon:0,    lat:85,   type:"ocean",    superficie:"14 M km²" },
  { nom:"Méditerranée",         lon:18,   lat:35,   type:"mer",      superficie:"2,5 M km²" },
  { nom:"Mer Rouge",            lon:37,   lat:20,   type:"mer",      superficie:"438 000 km²" },
  { nom:"Mer Noire",            lon:33,   lat:43,   type:"mer",      superficie:"436 000 km²" },
  { nom:"Mer Caspienne",        lon:51,   lat:42,   type:"lac_sale", superficie:"371 000 km²" },
  { nom:"Mer du Nord",          lon:4,    lat:56,   type:"mer",      superficie:"575 000 km²" },
  { nom:"Mer Baltique",         lon:19,   lat:58,   type:"mer",      superficie:"377 000 km²" },
  { nom:"Mer d'Arabie",         lon:65,   lat:18,   type:"mer",      superficie:"3,8 M km²" },
  { nom:"Golfe du Bengale",     lon:88,   lat:14,   type:"mer",      superficie:"2,2 M km²" },
  { nom:"Mer de Chine du Sud",  lon:114,  lat:14,   type:"mer",      superficie:"3,5 M km²" },
  { nom:"Mer de Chine orientale",lon:126, lat:29,   type:"mer",      superficie:"1,2 M km²" },
  { nom:"Mer du Japon",         lon:135,  lat:40,   type:"mer",      superficie:"1 M km²" },
  { nom:"Golfe Persique",       lon:51,   lat:27,   type:"golfe",    superficie:"251 000 km²" },
  { nom:"Golfe d'Aden",         lon:47,   lat:12,   type:"golfe",    superficie:"410 000 km²" },
  { nom:"Golfe de Guinée",      lon:3,    lat:3,    type:"golfe",    superficie:"1,5 M km²" },
  { nom:"Golfe du Mexique",     lon:-90,  lat:25,   type:"golfe",    superficie:"1,5 M km²" },
  { nom:"Mer des Caraïbes",     lon:-75,  lat:16,   type:"mer",      superficie:"2,7 M km²" },
  { nom:"Mer d'Okhotsk",        lon:150,  lat:55,   type:"mer",      superficie:"1,6 M km²" },
  { nom:"Mer de Béring",        lon:-173, lat:58,   type:"mer",      superficie:"2,3 M km²" },
  { nom:"Mer de Barents",       lon:40,   lat:74,   type:"mer",      superficie:"1,4 M km²" },
  { nom:"Lac Victoria",         lon:33,   lat:-1,   type:"lac",      superficie:"68 800 km²" },
  { nom:"Lac Tanganyika",       lon:29.5, lat:-7,   type:"lac",      superficie:"32 900 km²" },
  { nom:"Lac Malawi",           lon:34.5, lat:-12,  type:"lac",      superficie:"29 600 km²" },
  { nom:"Lac Tchad",            lon:14,   lat:13,   type:"lac",      superficie:"1 350 km² (2024)" },
];

// ── FLEUVES STRATÉGIQUES ──────────────────────────────────────────
const FLEUVES = [
  { nom:"Nil",        pts:[[32.9,30.5],[32.5,25],[33,20],[34.5,14],[33.5,10],[35,8],[35,5]],      long:"6 650 km", note:"Tensions Éthiopie/Égypte (barrage GERD)" },
  { nom:"Niger",      pts:[[-13.7,9.5],[-9,12],[-5,14],[-1,15],[2,14],[3.5,12],[4.5,6.5],[5,5]], long:"4 200 km", note:"Artère du Sahel, axe vital Mali/Niger/Nigeria" },
  { nom:"Congo",      pts:[[16,-5],[17,-3],[18,-2],[22,0],[25,2],[25,4]],                         long:"4 700 km", note:"2e débit mondial, RDC/Congo" },
  { nom:"Sénégal",    pts:[[-16.5,14.7],[-15,15],[-13,15.5],[-12,16],[-11,16],[-10.5,16.5]],     long:"1 790 km", note:"Frontière Sénégal/Mauritanie" },
  { nom:"Volta",      pts:[[1.3,6.4],[0,8],[-1,10],[-2.5,11],[-2,12],[0,13]],                    long:"1 600 km", note:"Ghana, barrage Akosombo" },
  { nom:"Euphrate",   pts:[[44,32],[43.5,34],[38.5,37],[37,38],[36,38]],                          long:"2 780 km", note:"Tensions Turquie/Syrie/Irak (eau)" },
  { nom:"Tigre",      pts:[[44,32],[44.5,33],[45,34],[43,36],[40,37],[38,38]],                    long:"1 950 km", note:"Irak, berceau des civilisations" },
  { nom:"Jourdain",   pts:[[35.6,31.8],[35.5,32.5],[35.6,33],[36,33.5]],                         long:"251 km",  note:"Conflit Israël/Palestine/Jordanie (eau)" },
  { nom:"Indus",      pts:[[67,24],[68,26],[70,28],[71,30],[71.5,32],[74,34],[77,36]],            long:"3 180 km", note:"Tensions Inde/Pakistan (Traité des Eaux)" },
  { nom:"Gange",      pts:[[88,22],[87,24],[85,25],[82,26],[80,27],[78,28],[77,29],[78,31]],      long:"2 525 km", note:"Sacré en Inde, pollution critique" },
  { nom:"Mékong",     pts:[[104,10],[105,11],[105.5,12],[105,14],[102,16],[100,18],[99,22],[97,26]],long:"4 350 km",note:"Barrages chinois vs pays aval (Laos, Thaïlande, Vietnam)" },
  { nom:"Yangtsé",    pts:[[121.5,31],[117,30],[115,30],[112,30],[107,29],[103,29],[100,27],[96,30],[91,29]],long:"6 300 km",note:"Barrage des Trois-Gorges, Chine" },
  { nom:"Amour",      pts:[[141,53],[135,48],[133,47],[130,48],[127,49],[123,52],[118,53]],       long:"4 440 km", note:"Frontière Russie/Chine" },
  { nom:"Volga",      pts:[[49.5,46],[47,48],[46,49],[46,52],[44,54],[43,55],[42,57],[42,58]],   long:"3 690 km", note:"Artère économique Russie" },
  { nom:"Danube",     pts:[[29,45],[28,45.5],[27,44.5],[26,44],[24,43.7],[22,43],[20,44],[18,44.5],[17,47],[16,48],[15,48],[14,48],[13,48]],long:"2 860 km",note:"Frontière naturelle Europe, traverse 10 pays" },
  { nom:"Amazone",    pts:[[-50,-1.5],[-55,-3],[-60,-3],[-65,-3.5],[-70,-4],[-74,-5],[-76,-4]],  long:"6 400 km", note:"20% eau douce mondiale" },
  { nom:"Congo (fleuve)",pts:[[16.3,-5.8],[17.5,-4],[18.5,-2.5],[19.5,-1],[22,1],[24,2],[25,2.5]],long:"4 700 km",note:"Frontière RDC/Congo-Brazzaville" },
  { nom:"Okavango",   pts:[[22,-17],[22,-18],[21,-19],[21,-20],[21,-21],[21.5,-22]],              long:"1 600 km", note:"Delta intérieur Botswana — réserve mondiale" },
];

// ── DÉTROITS ET CANAUX STRATÉGIQUES ──────────────────────────────
const DETROITS = [
  // Détroits
  { id:"gibraltar",  nom:"Détroit de Gibraltar",   lon:-5.35,  lat:36.15, type:"detroit",
    largeur:"14 km", trafic:"~100 000 navires/an",
    enjeu:"Verrou Atlantique–Méditerranée. OTAN surveille. Route migrants Maroc–Espagne.",
    ctrl:"Royaume-Uni / OTAN", risque:"moyen" },
  { id:"ormuz",      nom:"Détroit d'Ormuz",         lon:56.26,  lat:26.60, type:"detroit",
    largeur:"54 km", trafic:"21 M b/j pétrole (20% mondial)",
    enjeu:"Passage OBLIGATOIRE pétrole du Golfe. Menace iranienne permanente. 5e Flotte US (Bahreïn).",
    ctrl:"Iran (rive N) / Oman (rive S)", risque:"élevé" },
  { id:"malacca",    nom:"Détroit de Malacca",      lon:103.85, lat:1.35,  type:"detroit",
    largeur:"2,8 km min", trafic:"25% commerce mondial",
    enjeu:"Point d'étranglement Asie-Pacifique. 80% pétrole chinois. Piraterie historique.",
    ctrl:"Malaisie / Singapour / Indonésie", risque:"moyen" },
  { id:"bab_mandeb", nom:"Bab el-Mandeb",           lon:43.30,  lat:12.60, type:"detroit",
    largeur:"29 km", trafic:"7 M b/j + conteneurs Europe–Asie",
    enjeu:"Porte mer Rouge. Houthis yéménites bloquent/attaquent navires depuis 2023. Crise mondiale fret.",
    ctrl:"Djibouti (O) / Yémen (E)", risque:"critique" },
  { id:"bosphore",   nom:"Détroit du Bosphore",     lon:29.02,  lat:41.05, type:"detroit",
    largeur:"700 m min", trafic:"48 000 navires/an",
    enjeu:"Seul accès mer Noire. Convention Montreux (1936) : Turquie contrôle transit militaire. Clé conflit Ukraine.",
    ctrl:"Turquie (exclusive)", risque:"élevé" },
  { id:"dardanelles",nom:"Détroit des Dardanelles", lon:26.40,  lat:40.25, type:"detroit",
    largeur:"1,2 km min", trafic:"Lié Bosphore",
    enjeu:"Avec Bosphore : verrou mer Noire. Convention Montreux. Expédition des Dardanelles (1915).",
    ctrl:"Turquie (exclusive)", risque:"élevé" },
  { id:"dover",      nom:"Pas de Calais / Dover",   lon:1.50,   lat:51.00, type:"detroit",
    largeur:"34 km", trafic:"Route maritime la plus fréquentée au monde",
    enjeu:"Axe commerce Europe–Royaume-Uni post-Brexit. Câbles sous-marins critiques. Migrants Manche.",
    ctrl:"France / Royaume-Uni", risque:"faible" },
  { id:"tsugaru",    nom:"Détroit de Tsugaru",      lon:140.5,  lat:41.5,  type:"detroit",
    largeur:"20 km", trafic:"Accès Pacifique–Mer du Japon",
    enjeu:"Passage sous-marins russes et chinois. Surveillance JSDF. Tunnel Seikan dessous.",
    ctrl:"Japon", risque:"moyen" },
  { id:"lombok",     nom:"Détroit de Lombok",       lon:115.8,  lat:-8.8,  type:"detroit",
    largeur:"40 km", trafic:"Alternative Malacca (eaux profondes)",
    enjeu:"Route alternative pour porte-avions US (Malacca trop peu profond). Importance montante.",
    ctrl:"Indonésie", risque:"faible" },
  { id:"hormuz_alt", nom:"Golfe d'Oman (sortie Ormuz)",lon:58.0,lat:22.5, type:"detroit",
    largeur:"N/A", trafic:"Lié Ormuz",
    enjeu:"Zone de transit pétrole post-Ormuz. Patrouilles US/UK/FR. Incidents navires Iran.",
    ctrl:"International", risque:"élevé" },
  // Canaux
  { id:"suez_canal", nom:"Canal de Suez",           lon:32.55,  lat:30.68, type:"canal",
    largeur:"193 m", trafic:"~21 000 navires/an, 12% commerce mondial",
    enjeu:"Raccourci Europe–Asie (7 000 km vs Cap Bonne-Espérance). Revenus vitaux Égypte (10 Mds$/an). Crise Ever Given 2021. Dégradation trafic 2024 (Houthis).",
    ctrl:"Égypte (Autorité Canal Suez)", risque:"élevé" },
  { id:"panama",     nom:"Canal de Panama",         lon:-79.92, lat:9.08,  type:"canal",
    largeur:"55 m", trafic:"~14 000 navires/an, 6% commerce mondial",
    enjeu:"Axe Atlantique–Pacifique. Expansion chinoise (investissements portuaires). Tensions avec USA (Trump revendique canal). Sécheresse 2023–24 : restrictions trafic.",
    ctrl:"Panama (ACP)", risque:"moyen" },
  { id:"kiel",       nom:"Canal de Kiel",           lon:9.80,   lat:54.30, type:"canal",
    largeur:"102 m", trafic:"~25 000 navires/an (1er canal artificiel mondial par trafic)",
    enjeu:"Raccourci Mer du Nord–Baltique. Importance OTAN flanc est. Allemagne.",
    ctrl:"Allemagne", risque:"faible" },
  { id:"volga_don",  nom:"Canal Volga–Don",         lon:43.80,  lat:48.50, type:"canal",
    largeur:"18 m", trafic:"Commerce intérieur russe",
    enjeu:"Relie Mer Caspienne à Mer Noire. Axe logistique Russie. Importance militaire.",
    ctrl:"Russie", risque:"faible" },
  { id:"nord_est",   nom:"Route maritime du Nord",  lon:90,     lat:75,    type:"passage",
    largeur:"N/A", trafic:"Croissance rapide (fonte arctique)",
    enjeu:"Route Asie–Europe via Arctique (40% plus court). Russie contrôle/monétise. Fonte glaces accélère. Enjeu géopolitique majeur 2030+.",
    ctrl:"Russie (Zone économique exclusive)", risque:"moyen" },
  { id:"nord_ouest", nom:"Passage du Nord-Ouest",   lon:-100,   lat:75,    type:"passage",
    largeur:"N/A", trafic:"Émergent",
    enjeu:"Route Asie–Europe via Arctique canadien. Canada revendique eaux intérieures vs USA (libres). Montée des tensions arctiques.",
    ctrl:"Canada (revendiqué)", risque:"faible" },
];

// ── CHAÎNES DE MONTAGNES MAJEURES ─────────────────────────────────
const MONTAGNES = [
  { nom:"Himalaya",       lon:85,    lat:28,   alt:"8 849 m (Everest)", note:"Frontière Inde–Chine–Népal. Conflit LAC Ladakh. Château d'eau Asie (Indus, Gange, Brahmapoutre, Mékong, Yangtsé)." },
  { nom:"Hindu Kush",     lon:70,    lat:35,   alt:"7 708 m", note:"Afghanistan/Pakistan. Sanctuaire historique Taliban. Axe Silk Road. Source Indus/Kaboul." },
  { nom:"Caucase",        lon:44,    lat:42,   alt:"5 642 m (Elbrouz)", note:"Frontière Europe–Asie. Conflits : Ossétie, Abkhazie, Haut-Karabagh. Pipeline BTC (pétrole Caspienne–Méditerranée)." },
  { nom:"Zagros",         lon:48,    lat:33,   alt:"4 548 m", note:"Iran/Irak. Région kurde. Pétrole sous les contreforts." },
  { nom:"Taurus",         lon:34,    lat:37,   alt:"3 756 m", note:"Turquie du Sud. Barrages sur Euphrate/Tigre (tensions avec Syrie/Irak)." },
  { nom:"Atlas",          lon:-3,    lat:32,   alt:"4 167 m (Toubkal)", note:"Maroc/Algérie/Tunisie. Barrière climatique (arridification Sahara). Eau critique Maroc." },
  { nom:"Ahaggar",        lon:6,     lat:23,   alt:"2 918 m", note:"Algérie (Sahara central). Sanctuaire touareg. Uranium/gaz sous les plateaux." },
  { nom:"Aïr",            lon:8.5,   lat:17.5, alt:"1 900 m", note:"Niger. Zone sanctuaire JNIM/EIGS. Proximité mines uranium Arlit." },
  { nom:"Drakensberg",    lon:29,    lat:-29,  alt:"3 482 m", note:"Afrique du Sud/Lesotho. Source Orange et Tugela. Eau pour Johannesburg." },
  { nom:"Éthiopien (haut plateau)",lon:38,lat:9,alt:"4 620 m (Ras Dashen)",note:"Éthiopie. Source Nil Bleu (barrage GERD). Tension Éthiopie–Égypte–Soudan." },
  { nom:"Oural",          lon:60,    lat:56,   alt:"1 895 m", note:"Frontière Europe–Asie (géographique). Axe industriel Russie (Iekaterinbourg). Mines métaux." },
  { nom:"Altaï",          lon:88,    lat:50,   alt:"4 506 m", note:"Russie/Chine/Mongolie/Kazakhstan. Sources Ob et Irtych. Point de convergence cultures centre-asiatiques." },
  { nom:"Tianshan",       lon:80,    lat:42,   alt:"7 439 m", note:"Chine/Kirghizstan/Kazakhstan. 'Montagnes célestes'. Glaciers en recul (eau Asie centrale). Route Silk Road." },
  { nom:"Pamir",          lon:73,    lat:38,   alt:"7 649 m (Kongur)", note:"Tadjikistan/Afghanistan/Pakistan/Chine. 'Toit du monde'. Carrefour stratégique (Silk Road). Base militaire chinoise au Tadjikistan." },
  { nom:"Andes",          lon:-72,   lat:-20,  alt:"6 962 m (Aconcagua)",note:"Colonne vertébrale Amérique du Sud. Lithium (triangle Chili–Argentine–Bolivie). Eau andine pour côte pacifique." },
  { nom:"Rocheuses",      lon:-112,  lat:45,   alt:"4 399 m", note:"USA/Canada. Partage des eaux Atlantique–Pacifique. Aquifère Ogallala." },
  { nom:"Alpes",          lon:10,    lat:46,   alt:"4 808 m (Mont-Blanc)",note:"Europe centrale. Sources Rhin, Rhône, Po, Danube. Eau douce Europe. Tunnels ferroviaires stratégiques." },
  { nom:"Pyrénées",       lon:0,     lat:42.5, alt:"3 404 m", note:"Frontière France–Espagne. Barrière historique. Peu de cols praticables." },
  { nom:"Scandic (Kjølen)",lon:16,   lat:65,   alt:"2 469 m", note:"Norvège/Suède. Frontière naturelle. Ressources hydroélectriques. Arctique." },
];

// ── TERRITOIRES CONTESTÉS ET FRONTIÈRES DISPUTÉES ────────────────
const TERRITOIRES = [
  { id:"palestine_gb",  nom:"Gaza",                  lon:34.45,  lat:31.35,
    statut:"Territoire palestinien occupé (ONU) / Hamas",
    type:"conflit_actif",
    note:"Enclave 365 km² / 2,3 M hab. Blocus Israël/Égypte. Offensive israélienne depuis oct. 2023 (Hamas — attaque 7 oct. 2023). Crise humanitaire majeure. Statut juridique contesté.",
    parties:["Israël","Hamas","Autorité Palestinienne","Égypte"] },
  { id:"palestine_wb",  nom:"Cisjordanie",           lon:35.25,  lat:32.00,
    statut:"Territoire palestinien occupé (ONU) / Colonisation israélienne",
    type:"occupation",
    note:"Colonies israéliennes (700 000 colons). Autorité Palestinienne (zones A/B/C). 3 millions palestiniens. Colonisation accélérée sous gouvernement Netanyahu. Solution deux États en question.",
    parties:["Israël","Autorité Palestinienne"] },
  { id:"taiwan",        nom:"Taïwan",                lon:121,    lat:23.5,
    statut:"République de Chine (self-governed) / Revendiqué par RPC",
    type:"conflit_latent",
    note:"26 M hab. Économie avancée (TSMC — 60% semiconducteurs mondiaux avancés). Chine considère réunification 'inévitable'. USA arme Taïwan. Exercices militaires PLA croissants. Enjeu mondial critique.",
    parties:["Chine (RPC)","Taïwan (ROC)","USA"] },
  { id:"crimee",        nom:"Crimée",                lon:34,     lat:45,
    statut:"Annexée par Russie (2014) / Reconnue Ukraine et ONU comme ukrainienne",
    type:"annexion",
    note:"Péninsule stratégique mer Noire. Base navale de Sébastopol (Flotte Noire russe). Annexée par référendum non reconnu en 2014. Partiellement reconquise en mer (île des Serpents). Enjeu géopolitique majeur.",
    parties:["Russie","Ukraine","OTAN"] },
  { id:"donbass",       nom:"Donbass / Est Ukraine", lon:38,     lat:48,
    statut:"Partiellement occupé Russie depuis fév. 2022",
    type:"conflit_actif",
    note:"Donetsk, Louhansk, Zaporijjia, Kherson. Russie annexe 4 oblasts en sept. 2022 (non reconnu). Front ligne ~1 000 km. Guerre conventionnelle majeure en Europe depuis 1945.",
    parties:["Russie","Ukraine","OTAN (soutien)"] },
  { id:"mer_chine_s",   nom:"Mer de Chine du Sud",   lon:114,    lat:14,
    statut:"Revendications multiples (9 traits Chine)",
    type:"conflit_latent",
    note:"Chine revendique ~90% (ligne des 9 traits). Philippines, Vietnam, Malaisie, Brunei, Taïwan contestent. Îles artificielles chinoises (Spratleys). CJIN invalide revendications (2016, ignoré par Chine). Ressources: pétrole, gaz, pêche. USA patrouille liberté navigation.",
    parties:["Chine","Philippines","Vietnam","Malaisie","Brunei","Taïwan","USA"] },
  { id:"kashmir",       nom:"Cachemire",             lon:76,     lat:34,
    statut:"Disputé Inde–Pakistan–Chine",
    type:"conflit_latent",
    note:"Ligne de contrôle Inde–Pakistan depuis 1948. Inde révoque article 370 (2019) — Jammu-Cachemire territoire de l'Union. Chine contrôle Aksai Chin. 3 guerres indo-pakistanaises. Puissances nucléaires. Glaciers stratégiques (eau Indus).",
    parties:["Inde","Pakistan","Chine"] },
  { id:"nagorno",       nom:"Haut-Karabagh",         lon:46.8,   lat:40.0,
    statut:"Reconquis par Azerbaïdjan (sept. 2023)",
    type:"post_conflit",
    note:"Enclave arménienne reconnue azerbaïdjanaise. Exode total Arméniens (120 000). Corridors Zanguézour (accès Azerbaïdjan–Nakhitchevan–Turquie). Fin de facto République d'Artsakh. Bilan: dépeuplement total communauté arménienne.",
    parties:["Azerbaïdjan","Arménie","Russie (ex-garant)"] },
  { id:"western_sahara",nom:"Sahara Occidental",     lon:-13,    lat:24,
    statut:"Territoire non autonome (ONU) / Maroc 80% / Polisario 20%",
    type:"conflit_gele",
    note:"Ex-colonie espagnole. Maroc occupe depuis 1975 (Marche Verte). Polisario (Algérie) contrôle Hamada. ONU préconise référendum d'autodétermination (jamais tenu). Ressources : phosphates, pêche, éolien. France/USA reconnaissent souveraineté marocaine.",
    parties:["Maroc","Polisario (RASD)","Algérie","ONU"] },
  { id:"abkhazia",      nom:"Abkhazie",              lon:41.5,   lat:43,
    statut:"Indépendance reconnue par Russie (2008) / Territoire géorgien (ONU)",
    type:"conflit_gele",
    note:"République séparatiste pro-russe depuis guerre 2008. Reconnue par Russie, Syrie, Nicaragua, Venezuela, Nauru. Base militaire russe. Statut de protectorat de facto de Moscou.",
    parties:["Russie","Géorgie","UE"] },
  { id:"ossetia",       nom:"Ossétie du Sud",        lon:43.9,   lat:42.3,
    statut:"Indépendance reconnue par Russie (2008) / Territoire géorgien (ONU)",
    type:"conflit_gele",
    note:"Guerre russo-géorgienne août 2008. Contrôlée par Russie. Unification avec Ossétie du Nord (Russie) envisagée. Peuplement mixte ossète-géorgien.",
    parties:["Russie","Géorgie"] },
  { id:"falklands",     nom:"Îles Malouines (Falkland)",lon:-59,  lat:-51.5,
    statut:"Territoire britannique d'outre-mer / Revendiqué Argentine",
    type:"conflit_gele",
    note:"Guerre 1982 (Argentine vs Royaume-Uni). Autodétermination : 99,8% pour maintien britannique (2013). Ressources pétrolières offshore croissantes. Tensions permanentes Argentine–UK. Zone EEZ stratégique Atlantique Sud.",
    parties:["Royaume-Uni","Argentine"] },
  { id:"senkaku",       nom:"Îles Senkaku / Diaoyu",  lon:123.5, lat:25.8,
    statut:"Administrées Japon / Revendiquées Chine et Taïwan",
    type:"conflit_latent",
    note:"5 îles inhabitées. Patrouilles chinoises permanentes (zone ADIZ). Ressources pétrolières potentielles. Traité sécurité USA–Japon (Article 5) s'applique. Risque d'incident militaire élevé.",
    parties:["Japon","Chine","Taïwan","USA"] },
  { id:"spratleys",     nom:"Îles Spratleys",         lon:114,   lat:10,
    statut:"Revendiquées par 6 États",
    type:"conflit_latent",
    note:"Archipel mer de Chine du Sud. Îles artificielles chinoises militarisées (2014–2016). Enjeux: pêche, pétrole, routes maritimes. Base juridique : CNUDM vs ligne des 9 traits.",
    parties:["Chine","Vietnam","Philippines","Malaisie","Brunei","Taïwan"] },
  { id:"transniestrie", nom:"Transnistrie",           lon:29.5,  lat:47.2,
    statut:"République séparatiste pro-russe / Territoire moldave (ONU)",
    type:"conflit_gele",
    note:"Séparation de Moldavie en 1992. Troupes russes (groupe opérationnel). Centrale électrique à gaz russe (Cuciurgan — alimente Moldavie). Perturbée par guerre Ukraine (coupure gaz russe 2024). Inconnue géopolitique.",
    parties:["Russie","Moldavie","UE"] },
];

// ── VILLES STRATÉGIQUES MONDIALES ─────────────────────────────────
const VILLES = [
  // Afrique Subsaharienne / Sahel
  { nom:"Bamako",     lon:-8.00,  lat:12.65, pays:"Mali",          cat:"capital",  pop:"3,5 M", note:"Junte AES, Wagner", iso:"MLI" },
  { nom:"Niamey",     lon:2.11,   lat:13.51, pays:"Niger",         cat:"capital",  pop:"1,3 M", note:"Junte, uranium", iso:"NER" },
  { nom:"Ouagadougou",lon:-1.53,  lat:12.36, pays:"Burkina Faso",  cat:"capital",  pop:"3,7 M", note:"Junte, AES", iso:"BFA" },
  { nom:"N'Djaména",  lon:15.05,  lat:12.10, pays:"Tchad",         cat:"capital",  pop:"1,7 M", note:"Pivot régional, France", iso:"TCD" },
  { nom:"Dakar",      lon:-17.44, lat:14.69, pays:"Sénégal",       cat:"hub",      pop:"3,7 M", note:"Hub Atlantique" },
  { nom:"Abidjan",    lon:-4.03,  lat:5.35,  pays:"Côte d'Ivoire", cat:"hub",      pop:"6,3 M", note:"1er port AOF", iso:"CIV" },
  { nom:"Lagos",      lon:3.38,   lat:6.45,  pays:"Nigeria",       cat:"megacity", pop:"25 M",  note:"1ère métropole Afrique", iso:"NGA" },
  { nom:"Kinshasa",   lon:15.31,  lat:-4.32, pays:"RDC",           cat:"megacity", pop:"17 M",  note:"Cobalt, coltan, instabilité" },
  { nom:"Nairobi",    lon:36.82,  lat:-1.29, pays:"Kenya",         cat:"hub",      pop:"5,5 M", note:"Hub Afrique de l'Est" },
  { nom:"Addis-Abeba",lon:38.74,  lat:9.03,  pays:"Éthiopie",      cat:"capital",  pop:"5,5 M", note:"Siège UA, barrage GERD" },
  { nom:"Le Caire",   lon:31.23,  lat:30.06, pays:"Égypte",        cat:"megacity", pop:"22 M",  note:"Capital Nil, Suez, Arabie", iso:"EGY" },
  { nom:"Khartoum",   lon:32.56,  lat:15.55, pays:"Soudan",        cat:"capital",  pop:"7 M",   note:"Guerre civile FAR vs FADS 2023" },
  { nom:"Djibouti",   lon:43.15,  lat:11.59, pays:"Djibouti",      cat:"strategic",pop:"630 K", note:"5 bases militaires étrangères" },
  // Moyen-Orient
  { nom:"Riyad",      lon:46.68,  lat:24.69, pays:"Arabie Saoudite",cat:"capital", pop:"7,7 M", note:"Pétrole, Vision 2030" },
  { nom:"Téhéran",    lon:51.39,  lat:35.69, pays:"Iran",          cat:"capital",  pop:"9,5 M", note:"Nucléaire, Axe résistance", iso:"IRN" },
  { nom:"Tel-Aviv/Jérusalem",lon:35.21,lat:31.78,pays:"Israël",    cat:"capital",  pop:"4,5 M", note:"Gaza, Cisjordanie, Iran", iso:"ISR" },
  { nom:"Istanbul",   lon:28.95,  lat:41.01, pays:"Turquie",       cat:"megacity", pop:"15,8 M",note:"Bosphore, OTAN, pivot" },
  { nom:"Bagdad",     lon:44.44,  lat:33.34, pays:"Irak",          cat:"capital",  pop:"8,9 M", note:"Milices pro-Iran, pétrole" },
  { nom:"Damas",      lon:36.29,  lat:33.51, pays:"Syrie",         cat:"capital",  pop:"2,3 M", note:"Post-Assad (déc. 2024), reconstruction" },
  { nom:"Sanaa",      lon:44.19,  lat:15.35, pays:"Yémen",         cat:"conflict", pop:"3,9 M", note:"Houthis, guerre civile, Bab el-Mandeb" },
  { nom:"Aden",       lon:45.02,  lat:12.78, pays:"Yémen",         cat:"strategic",pop:"900 K", note:"Port stratégique Golfe d'Aden" },
  // Asie Centrale / Caucase
  { nom:"Astana",     lon:71.43,  lat:51.19, pays:"Kazakhstan",    cat:"capital",  pop:"1,3 M", note:"Uranium, OCS, hydrocarbures" },
  { nom:"Bakou",      lon:49.87,  lat:40.41, pays:"Azerbaïdjan",   cat:"capital",  pop:"2,3 M", note:"Pipeline BTC, post-Karabagh" },
  { nom:"Tbilissi",   lon:44.83,  lat:41.69, pays:"Géorgie",       cat:"capital",  pop:"1,3 M", note:"Pro-UE, Ossétie/Abkhazie" },
  // Asie du Sud
  { nom:"New Delhi",  lon:77.21,  lat:28.63, pays:"Inde",          cat:"capital",  pop:"32 M",  note:"BRICS, SCO, puissance montante" },
  { nom:"Islamabad",  lon:73.07,  lat:33.72, pays:"Pakistan",      cat:"capital",  pop:"1,2 M", note:"Nucléaire, Taliban, Cachemire" },
  { nom:"Kaboul",     lon:69.17,  lat:34.52, pays:"Afghanistan",   cat:"capital",  pop:"4,6 M", note:"Taliban, Silk Road, opium" },
  // Asie-Pacifique
  { nom:"Pékin",      lon:116.40, lat:39.93, pays:"Chine",         cat:"capital",  pop:"22 M",  note:"SCO, BRI, Taiwan, Mer de Chine", iso:"CHN" },
  { nom:"Shanghai",   lon:121.47, lat:31.23, pays:"Chine",         cat:"megacity", pop:"28 M",  note:"1er port mondial", iso:"CHN" },
  { nom:"Tokyo",      lon:139.69, lat:35.68, pays:"Japon",         cat:"megacity", pop:"38 M",  note:"QUAD, réarmement, Senkaku" },
  { nom:"Séoul",      lon:126.98, lat:37.57, pays:"Corée du Sud",  cat:"capital",  pop:"10 M",  note:"OTAN-partenaire, K-chips, Corée du Nord" },
  { nom:"Singapour",  lon:103.82, lat:1.35,  pays:"Singapour",     cat:"hub",      pop:"5,9 M", note:"Détroit Malacca, hub financier" },
  { nom:"Taipei",     lon:121.56, lat:25.04, pays:"Taïwan",        cat:"capital",  pop:"2,7 M", note:"TSMC, semiconducteurs, menace PLA" },
  // Europe
  { nom:"Moscou",     lon:37.62,  lat:55.75, pays:"Russie",        cat:"capital",  pop:"12,5 M",note:"Guerre Ukraine, OTAN, nucléaire", iso:"RUS" },
  { nom:"Berlin",     lon:13.38,  lat:52.52, pays:"Allemagne",     cat:"capital",  pop:"3,8 M", note:"Zeitenwende, 1ère économie UE" },
  { nom:"Paris",      lon:2.35,   lat:48.85, pays:"France",        cat:"capital",  pop:"11 M",  note:"P5 ONU, dissuasion nucléaire" },
  { nom:"Washington DC",lon:-77.04,lat:38.90,pays:"États-Unis",    cat:"capital",  pop:"7 M",   note:"OTAN, 1ère armée mondiale", iso:"USA" },
  { nom:"Kiev",       lon:30.52,  lat:50.45, pays:"Ukraine",       cat:"conflict", pop:"3,7 M", note:"Guerre Russie, candidat UE/OTAN", iso:"UKR" },
  // Amériques
  { nom:"New York",   lon:-74.01, lat:40.71, pays:"États-Unis",    cat:"megacity", pop:"20 M",  note:"ONU, finance mondiale", iso:"USA" },
  { nom:"Houston",    lon:-95.37, lat:29.76, pays:"États-Unis",    cat:"hub",      pop:"7 M",   note:"Hub pétrole et gaz (Gulf Coast)", iso:"USA" },
  { nom:"Panama City",lon:-79.52, lat:8.99,  pays:"Panama",        cat:"strategic",pop:"1,1 M", note:"Canal de Panama" },
  // Tripoli/Benghazi pour Libye
  { nom:"Tripoli",    lon:13.19,  lat:32.89, pays:"Libye",         cat:"capital",  pop:"1,2 M", note:"GNU, guerre civile", iso:"LBY" },
  { nom:"Le Cap",     lon:18.42,  lat:-33.92,pays:"Afrique du Sud",cat:"hub",      pop:"4,7 M", note:"Cap Bonne-Espérance", iso:"ZAF" },
];

// ── FICHES PAYS EXHAUSTIVES ────────────────────────────────────────
const PAYS_DATA = {
  // ── AFRIQUE DE L'OUEST / SAHEL ────────────────────────────────
  "MLI": {
    nom:"Mali", capitale:"Bamako", pop:"23 M", superficie:"1 240 192 km²",
    regime:"Junte militaire (transition CNSP/CNT depuis 2021)",
    langue:"Français (officiel), bambara, peul, soninké, touareg",
    religion:"Islam sunnite 95%, christianisme 2%, animisme 3%",
    geo:"Sahel et Sahara. Enclavé. Niger traverse le pays du SO au NE. Delta intérieur Niger (zone humide critique). Nord : désert (Azawad, Kidal, Gao). Sud : savane soudanienne fertile.",
    ressources:["Or (1er Afrique de l'Ouest)","Coton","Uranium (faible)","Phosphates","Énergie hydroélectrique (barrage Sélingué, Félou)"],
    energie:"Dépendant importations pétrole. Hydraulique limité. Solaire en développement. Fréquentes coupures.",
    economie:"PIB ~$20 Mds. Agriculture 35% PIB. Or : 60% exportations. Coton. Forte dépendance aide internationale. Embargo CEDEAO (levé 2022) a coûté ~$2 Mds.",
    histoire:"Empire du Mali (13e s.), Tombouctou centre intellectuel islam. Colonisation française 1890-1960. Indépendance 1960. Coups d'État 1968 (Moussa Traoré), 1991 (démocratisation), 2012 (Sanogo), 2020 et 2021 (Goïta).",
    politique:"Alliance avec Russie (Wagner/Africa Corps). Rupture avec France (fin Barkhane 2022, Takuba 2022). Membre fondateur AES. Suspension CEDEAO. Tensions avec Algérie (frontière nord). Referendum constitutionnel 2023.",
    conflits:"JNIM (Groupe de Soutien à l'Islam et aux Musulmans, filiale AQ). EIGS (État islamique Sahara). MNLA et CMA (Touareg Azawad). Front homogène fragile FAMa + Wagner.",
    voisins:{
      "Algérie":"Frontière nord (1 376 km). Acteur diplomatique clé. Tensions sur retrait MINUSMA et présence Wagner.",
      "Mauritanie":"Frontière ouest. Flux réfugiés. Coopération sécuritaire.",
      "Sénégal":"Frontière SO. Bons rapports historiques mais tensions politiques (soutien CEDEAO).",
      "Côte d'Ivoire":"Frontière sud. Principal partenaire économique. Soutien CEDEAO contre junte.",
      "Burkina Faso":"Frontière SO. Même situation junte. Alliance AES. Jonction zones jihadistes.",
      "Niger":"Frontière est. Alliance AES. Zone conflit commune (région Ménaka–Tillabéri).",
      "Guinée":"Frontière SO. Transit marchandises port Conakry."
    }
  },

  "NER": {
    nom:"Niger", capitale:"Niamey", pop:"26 M", superficie:"1 267 000 km²",
    regime:"Junte militaire (CNSP depuis juil. 2023)",
    langue:"Français (officiel), haoussa, zarma, tamasheq, kanouri",
    religion:"Islam sunnite 99%",
    geo:"Sahel et Sahara. Enclavé. Fleuve Niger (SO). Massif de l'Aïr (nord). Lac Tchad (SE). Dépression du Ténéré (désert central). Région de Tillabéri (triple frontière — zone conflit critique).",
    ressources:["Uranium (7e mondial, mines Arlit — Orano)","Pétrole (Agadem — CNPC)","Or","Charbon","Énergie solaire potentiel élevé"],
    energie:"Uranium exporté brut (pas d'enrichissement). Pétrole : pipeline vers Cotonou. 80% population sans électricité. Import électricité Nigeria.",
    economie:"PIB ~$14 Mds. Un des pays les plus pauvres monde (IDH rang 189/191). Agriculture subsistance. Uranium et pétrole : revenus État mais peu redistribués.",
    histoire:"Sultanat de Sokoto, Empire Songhaï, Touareg. Colonisation 1900-1960. Indépendances 1960. Coups d'État 1974, 1996, 1999, 2010, 2023. Alternance démocratique 2021 (Bazoum) interrompue par coup.",
    politique:"Coup juillet 2023 : renversement Bazoum (partenaire occidental clé). Expulsion ambassadeur France, fermeture espace aérien. Fermeture base drones US Agadez 201. Rapprochement Russie/AES. Accord pétrolier CNPC (Chine). Suspensions CEDEAO.",
    conflits:"JNIM actif région Tillabéri (triple frontière). EIGS actif Diffa (est). Boko Haram (ex-ISWAP) lac Tchad. Route migratoire Nord–Afrique (Agadez).",
    voisins:{
      "Algérie":"Frontière nord. Coopération sécuritaire (mais tendue). Transit migrants et trafiquants.",
      "Libye":"Frontière NO. Porosité totale. Flux armes et migrants.",
      "Tchad":"Frontière est. Lac Tchad partagé. Coopération G5 Sahel (suspendu).",
      "Nigeria":"Frontière sud. Principal partenaire économique. Import électricité.",
      "Bénin":"Frontière SO. Pipeline pétrole Agadem–Cotonou (CNPC).",
      "Burkina Faso":"Frontière SO. Alliance AES. Zone conflit commune.",
      "Mali":"Frontière ouest. Alliance AES. Zones jihadistes communes."
    }
  },

  "BFA": {
    nom:"Burkina Faso", capitale:"Ouagadougou", pop:"23 M", superficie:"274 200 km²",
    regime:"Junte militaire (MPSR II — Traoré depuis oct. 2022)",
    langue:"Français (officiel), mooré, dioula, fulfuldé (60+ langues)",
    religion:"Islam 61%, christianisme 24%, animisme 15%",
    geo:"Plateau de l'Adrar des Ifoghas au nord. Trois bassins versants (Volta Rouge, Blanche, Noire). Sahel aride au nord, savane au sud. Enclavé. Zone triple frontière (Burkina–Mali–Niger) : épicentre jihadiste.",
    ressources:["Or (4e producteur africain)","Zinc","Manganèse","Coton","Énergie solaire"],
    energie:"Dépendant imports pétrole. Barrage Bagré (hydraulique). Coupures fréquentes. 50% artisanat minier or.",
    economie:"PIB ~$19 Mds. Agriculture 25% PIB. Or 60%+ exportations. Embargo commercial jihadiste (nord pays). Coûts sécurité explosent.",
    histoire:"Royaumes Mossi (fondés 11e s., résistance colonisation jusqu'en 1896). Colonisation française 1896-1960. Haute-Volta → Burkina Faso (1984, Sankara). Thomas Sankara : révolution panafricaine, assassinat 1987 (Compaoré). Compaoré : 27 ans, renversé 2014. Coups 2022 (Damiba jan., Traoré oct.).",
    politique:"Ibrahim Traoré (le + jeune chef d'État monde ~35 ans). Discours souverainiste et anti-France. Expulsion ambassadeur Fr, fermeture RFI/France 24. Russie/Wagner. AES. Retrait CEDEAO. Connexion Azerbaïdjan (armes anti-drone).",
    conflits:"Plus de 11 000 morts depuis 2015. ~2 M déplacés internes. 40% territoire non contrôlé État. JNIM dominant (nord et est). EIGS (est). Dozos (milices auto-défense, accusations exactions).",
    voisins:{
      "Mali":"Frontière nord/NO. Zone conflit fusionnée. Alliance AES.",
      "Niger":"Frontière nord/NE. Zone conflit commune (Sahel).",
      "Bénin":"Frontière est. Front jihadiste émergent (Pendjari/W).",
      "Togo":"Frontière est. Menace progression jihadiste vers côte.",
      "Ghana":"Frontière sud. Stable. Pression humanitaire (réfugiés).",
      "Côte d'Ivoire":"Frontière SO. Tensions (soutien CEDEAO). Flux réfugiés."
    }
  },

  "TCD": {
    nom:"Tchad", capitale:"N'Djaména", pop:"18 M", superficie:"1 284 000 km²",
    regime:"Transition (Mahamat Idriss Déby, élu mai 2024)",
    langue:"Français et arabe (officiels), sara, kanembou, arabes tchadiens (120+ langues)",
    religion:"Islam 55%, christianisme 40%, animisme 5%",
    geo:"Lac Tchad (SE, réduit de 90% depuis 1960). Tibesti (massif saharien, 3 415 m). Dépression du Bodélé (zone poussiéreuse mondiale). Bassin du Chari-Logone (agriculture sud). Position géostratégique centrale : carrefour 6 frontières.",
    ressources:["Pétrole (pipeline Tchad–Cameroun, Doba)","Or","Uranium (Tibesti, peu exploité)","Pêche lac Tchad (effondrement)"],
    energie:"Pipeline Doba–Kribi (Cameroun) depuis 2003. 80% revenus État = pétrole. Réserves déclinantes.",
    economie:"PIB ~$12 Mds. Pétrole 60% revenus État. Agriculture subsistance (sud). Extrême pauvreté. Réfugiés : 600 000 (Soudan, CAR, Nigeria).",
    histoire:"Royaume Kanem-Bornou (9e-19e s.). Colonisation française 1900-1960. Guerre civile et interventions France répétées (opération Épervier puis Barkhane). Hissène Habré (1982-1990, soutenu USA vs Libye). Idriss Déby (1990-2021, mort au front Tibesti).",
    politique:"Seul pays sahélien maintenant partenariat avec France (opération Éclaireur). Mahamat Déby élu 2024. Relations complexes avec Soudan (guerre civile 2023 = 600 000 réfugiés). Médiateur régional. Membre non-AES.",
    conflits:"Boko Haram/ISWAP lac Tchad. Milices inter-communautaires (éleveurs-agriculteurs). Débordement guerre civile soudanaise. Tibesti : rébellion FACT (Libye).",
    voisins:{
      "Soudan":"Frontière est. Guerre civile 2023 : afflux massif réfugiés (600 000+). Darfour déstabilise est Tchad.",
      "Libye":"Frontière nord. Flux armes et mercenaires. FACT (rébellion) opère depuis Libye.",
      "Niger":"Frontière nord-ouest. Lac Tchad partagé. Coopération anti-Boko Haram.",
      "Nigeria":"Frontière SO. Lac Tchad partagé. FMN lac Tchad. 1er partenaire économique.",
      "Cameroun":"Frontière SO. Pipeline pétrole. Coopération militaire.",
      "RCA":"Frontière sud. Réfugiés. Instabilité frontalière."
    }
  },

  // ── GOLFE DE GUINÉE ───────────────────────────────────────────
  "NGA": {
    nom:"Nigeria", capitale:"Abuja (Lagos éco.)", pop:"225 M", superficie:"923 768 km²",
    regime:"République fédérale présidentielle (Tinubu depuis 2023)",
    langue:"Anglais (officiel), haoussa, yoruba, igbo (500+ langues)",
    religion:"Islam 50% (nord), christianisme 50% (sud)",
    geo:"Delta du Niger (pétrole, mangroves). Plateau de Jos (centre). Lac Tchad (NE). Montagnes Cameroun (SE). Sahel aride (nord). Savane (centre). Forêt tropicale (sud). Façade atlantique (800 km).",
    ressources:["Pétrole (1,5 M b/j — 1er Afrique)","Gaz naturel (3e réserves Afrique)","Or","Charbon","Columbite-tantalite","Agriculture (cacao, palmier)"],
    energie:"Producteur et exportateur majeur. Mais capacité raffinage insuffisante : importe produits raffinés. Blackouts chroniques. Décommission subsides carburant 2023 (choc social). NLNG (GNL).",
    economie:"PIB ~$440 Mds (1ère économie Afrique). Mais PIB/hab faible (~$2 000). Pétrole 90% exports. Diaspora : 25 Mds$ remittances. Inflation 30%+ (2024). Naira déprécié.",
    histoire:"Royaumes Bénin, Kanem-Bornou, Songhaï. Sultanat de Sokoto (1804). Colonisation britannique (amalgamation 1914). Indépendance 1960. Guerre civile Biafra 1967-70 (1-3 M morts). Dictatures militaires. Retour démocratie 1999.",
    politique:"Fédéralisme fragile (36 États). Ceinture du milieu (conflits éleveurs-agriculteurs). Élections contestées (Tinubu 2023). Séparatisme Biafra (IPOB–SE). Réforme monétaire/subventions 2023. Influence régionale CEDEAO (soutien démocratie).",
    conflits:"Boko Haram/ISWAP (nord-est, Borno). Piraterie golfe Guinée (en recul). Banditisme nord-ouest (Zamfara). IPOB sud-est. Conflits éleveurs-agriculteurs (ceinture du milieu).",
    voisins:{
      "Niger":"Frontière nord. Lac Tchad. Import électricité Niger.",
      "Tchad":"Frontière NE. Lac Tchad (FMN). Boko Haram partagé.",
      "Cameroun":"Frontière est. Péninsule de Bakassi (arbitrage CIJ 2002, attribué Cameroun). Relations commerciales.",
      "Bénin":"Frontière ouest. Commerce, contrebande carburant."
    }
  },

  "CIV": {
    nom:"Côte d'Ivoire", capitale:"Yamoussoukro / Abidjan (éco.)", pop:"27 M", superficie:"322 463 km²",
    regime:"République présidentielle (Ouattara depuis 2011, 3e mandat controversé 2020)",
    langue:"Français (officiel), dioula, bété, baoulé (70+ langues)",
    religion:"Islam 42%, christianisme 34%, animisme 24%",
    geo:"Côte atlantique (600 km). Forêt tropicale (sud–centre, en recul). Savane (nord). Pas de grands fleuves navigables. Frontière naturelle peu marquée au nord (Mali, Burkina).",
    ressources:["Cacao (1er mondial, 45% production mondiale)","Café","Or","Pétrole offshore","Caoutchouc","Palmier à huile"],
    energie:"Barrage Kossou. Gaz naturel offshore. Producteur électricité sous-régional (export Ghana, Burkina). CIPREL et CIE (privés).",
    economie:"PIB ~$70 Mds (croissance ~7%/an). Cacao = économie de rente. Secteur financier (BIAO, NSIA). Abidjan : capitale économique AOF. Endettement croissant.",
    histoire:"Royaumes Agni, Baoulé, Mandé. Colonisation française 1893. Indépendance 1960 (Houphouët-Boigny — père fondateur, modèle développement). 'Ivoiritarisation' (années 90). Guerre civile 2002-2011 (rébellion FN–GB). Crise post-électorale 2010-11 (Gbagbo–Ouattara, 3 000 morts).",
    politique:"Stabilité retrouvée sous Ouattara (FMI, France). Mais tensions politiques (Bédié mort 2023, opposition fragmentée). Risque contamination jihadiste nord (Woroba, Hambol). Influence économique régionale (BCEAO à Dakar, BRVM à Abidjan).",
    conflits:"Contraction jihadiste nord (attaques Kafolo 2020, Tehini 2021). Tensions inter-communautaires (peuls-autochtones). Surveillance renforcée frontière Burkina.",
    voisins:{
      "Burkina Faso":"Frontière nord. Flux réfugiés (100 000+). Progression jihadiste alarmante.",
      "Mali":"Frontière nord-ouest. Alliance CEDEAO. Transit routier.",
      "Guinée":"Frontière nord-ouest. Relations commerciales. Même fragilité institutionnelle.",
      "Libéria":"Frontière ouest. Post-conflit. Présence UNMIL révolue.",
      "Ghana":"Frontière est. Compétition cacao et or. Coopération sécuritaire."
    }
  },

  // ── MAGHREB ───────────────────────────────────────────────────
  "LBY": {
    nom:"Libye", capitale:"Tripoli (GNU) / Benghazi (GNS)", pop:"7 M", superficie:"1 759 540 km²",
    regime:"État fragmenté : GNU (Tripoli, PM Dbeibah) / GNS (Benghazi, Haftar) — guerre civile",
    langue:"Arabe (officiel), berbère (amazigh)",
    religion:"Islam sunnite 97%",
    geo:"99% désert saharien. Côte méditerranéenne (1 770 km). Golfe de Syrte (stratégique). Fezzan (sud — route trans-saharienne migrants). Cyrénaque (est — pétrole). Tripolitaine (ouest — capitale). Frontières poreuses (4 000 km) avec 6 pays.",
    ressources:["Pétrole (1,2 M b/j — 1ères réserves Afrique)","Gaz naturel","Eau fossile (Great Man-Made River)"],
    energie:"Économie rentière. Pétrole = 95% revenus État. Deux NOC concurrentes (Tripoli et Benghazi). Pipelines vers Europe (Greenstream vers Italie — 8 Mds m³/an). ENOC.",
    economie:"PIB ~$60 Mds (très volatile). Richesse pétrolière non redistribuée. Deux banques centrales concurrentes. Économie de rente paralysée par guerre.",
    histoire:"Phénicie, Rome (Tripolitaine), Empire Ottoman. Colonisation italienne 1911-1943 (guerre d'Agadir, résistance Senoussi–Omar Moukhtar). Royaume de Libye 1951. Kadhafi coup 1969 — Jamahiriya 42 ans. Révolution 2011 (OTAN, NTC). Fragmentation depuis 2014.",
    politique:"Deux gouvernements, deux parlements, deux banques centrales. Wagner/Africa Corps soutient Haftar (GNS est). Turquie soutient GNU (Tripoli). Émirats, Russie, Égypte : pro-Haftar. Qatar, Turquie : pro-GNU. Principal hub migration vers Europe (côtes Zaouïa, Zwara). Armes prolifèrent vers Mali, Niger, Tchad.",
    conflits:"Guerre civile chronique. Milices innombrables. Béliers Wagner. Flux armes vers Sahel. Opérations EUNAVFOR MED.",
    voisins:{
      "Tunisie":"Frontière nord-ouest. 1 M Libyens en Tunisie. Commerce et contrebande. Terroristes transits.",
      "Algérie":"Frontière ouest. 980 km. Algérie refuse intervention mais surveille.",
      "Niger":"Frontière sud. Route migration centrale. Flux armes.",
      "Tchad":"Frontière sud-est. FACT (rébellion) basée en Libye.",
      "Soudan":"Frontière est. Flux armes vers Darfour.",
      "Égypte":"Frontière est. Égypte soutient Haftar (Sissi). Opérations CIE frontière."
    }
  },

  "EGY": {
    nom:"Égypte", capitale:"Le Caire", pop:"107 M", superficie:"1 001 449 km²",
    regime:"République présidentielle autoritaire (Sissi depuis 2014, 3e mandat 2024)",
    langue:"Arabe égyptien (dialecte dominant), arabe standard officiel",
    religion:"Islam sunnite 90%, Coptes 10%",
    geo:"99% population sur 4% territoire (vallée et delta du Nil). Sinaï (péninsule, désert, frontière Gaza). Désert Libyen (ouest). Désert Arabique (est). Canal de Suez (163 km). Façade méditerranéenne et mer Rouge.",
    ressources:["Pétrole et gaz (offshore Méditerranée — ENI Zohr)","Phosphates","Or","Canal de Suez (revenus)","Tourisme","Agriculture Nil"],
    energie:"Gaz naturel (découverte Zohr 2015 = autosuffisance). Pétrole déclinant. Nucléaire (centrale El-Dabaa, Russie Rosatom). Éolien (Golfe de Suez). Barrage Assouan.",
    economie:"PIB ~$395 Mds. Revenus Suez ~10 Mds$/an. Tourisme ~14 Mds$/an. Remittances diaspora ~32 Mds$. Crise monétaire 2022-24 (dépréciation livre). Accord FMI ~3 Mds$. Inflation 40%.",
    histoire:"Civilisation pharaonique (3 000 ans). Ptolémées, Rome, Byzance. Conquête arabe 641. Mamelouks, Ottomans. Napoléon 1798. Muhammad Ali (1805-1848, modernisation). Colonisation britannique 1882. Indépendance 1952 (Nasser, nationalisation Suez 1956). Guerres 1948, 1956, 1967, 1973 avec Israël. Paix 1979 (Camp David). Moubarak 30 ans. Printemps arabe 2011. Morsi. Sissi 2013.",
    politique:"État sécuritaire. Frères Musulmans bannis. Gaza : Égypte médiateur clé mais frontière Rafah fermée (accusations). Barrage GERD (Éthiopie) : casus belli potentiel (Nil = 95% eau Égypte). Relations complexes avec Israël (froid mais fonctionnel). Tensions avec Turquie (Libye). FMI/Golfe : soutien financier.",
    conflits:"Sinai Province (EIGS–Sinaï). Guerre Gaza : pressions sur Rafah. GERD : escalade diplomatique avec Éthiopie et Soudan.",
    voisins:{
      "Israël":"Frontière nord-est (Sinaï). Paix froide Camp David 1979. Gaza : coordination militaire partielle.",
      "Gaza / Palestine":"Frontière Rafah. Humanitaire et sécurité. Pression internationale.",
      "Libye":"Frontière ouest. Soutien Haftar. Opérations anti-terroristes frontière.",
      "Soudan":"Frontière sud. Contentieux Halaïb-Shalateen. Guerre civile soudanaise : réfugiés.",
      "Éthiopie":"Pas de frontière directe. GERD : conflit existentiel eau du Nil."
    }
  },

  // ── MOYEN-ORIENT ────────────────────────────────────────────
  "IRN": {
    nom:"Iran", capitale:"Téhéran", pop:"87 M", superficie:"1 648 195 km²",
    regime:"République islamique (Guide suprême Khamenei + Président Pezeshkian depuis 2024)",
    langue:"Persan (officiel), azéri, kurde, arabe, baloutche",
    religion:"Islam chiite 90-95%, sunnite 5%, minorités (Zoroastriens, Chrétiens, Juifs)",
    geo:"Plateau iranien (altitude moyenne 1 000 m). Monts Zagros (SO). Alborz (N, source Caspienne). Déserts Kavir et Lut (centre). Accès golfe Persique et mer d'Oman (1 900 km côte). Pas d'accès Méditerranée.",
    ressources:["Pétrole (4e réserves mondiales — 150 Mds barils)","Gaz naturel (2e réserves mondiales)","Cuivre","Zinc","Uranium"],
    energie:"Autosuffisant hydrocarbures. Nucléaire civil controversé (enrichissement 60-84% uranium). Sanctions bloquent exportation (~400 000 b/j vs potentiel 4 M b/j). Échanges shadow via Chine, Irak.",
    economie:"PIB ~$367 Mds (PPP ~$1 500 Mds). Sanctions massives depuis 2012 et 2018 (JCPOA, INSTEX). Inflation 40%+. Rial effondré. Économie informelle massive. Relations économiques Chine (accord 25 ans, ~400 Mds$).",
    histoire:"Perse achéménide (Cyrus le Grand). Alexandre. Sassanides. Conquête arabe 651. Safavides (16e s. — chiisme d'État). Qajars. Mossadegh (nationalisation pétrole 1951, coup CIA 1953). Shah Pahlavi. Révolution islamique Khomeini 1979. Guerre Iran-Irak 1980-88 (1 M morts).",
    politique:"'Axe de la Résistance' : Hezbollah (Liban), Hamas (Gaza), Houthis (Yémen), milices irakiennes, Assad (Syrie — chute déc. 2024). Programme nucléaire : accord JCPOA 2015 abandonné par Trump 2018. Négociations intermittentes. Opération April 2024 (drones et missiles vs Israël). Répression manifestations (Mahsa Amini 2022).",
    conflits:"Proxy guerres : Gaza, Liban, Yémen, Irak, Syrie. Programme nucléaire. Tensions Golfe. Répression interne. Baloutchistan (Jaish ul-Adl). Kurdes (PJAK).",
    voisins:{
      "Irak":"Frontière ouest. Influence milices chiites (PMF). Économie interdépendante.",
      "Afghanistan":"Frontière est. Taliban : relations pragmatiques mais tensions (eau Helmand, réfugiés).",
      "Pakistan":"Frontière est. Baloutchistan partagé. Tensions (Jaish ul-Adl).",
      "Turquie":"Frontière NO. Compétition influence région (Syrie, Azerbaïdjan). Échanges commerciaux.",
      "Azerbaïdjan":"Frontière nord. Tensions (Karabagh, relations Israël-Azerbaïdjan).",
      "Arabie Saoudite":"Pas de frontière directe. Rivalité chiite-sunnite. Accord Pékin 2023 (normalisation)."
    }
  },

  "ISR": {
    nom:"Israël", capitale:"Jérusalem (controversée) / Tel-Aviv (facto)", pop:"10 M (+ 5,5 M Palestinians)", superficie:"22 145 km² (+7 000 Cis.)",
    regime:"Démocratie parlementaire (Netanyahu, coalition droite-extrême droite depuis 2022)",
    langue:"Hébreu et arabe (officiels)",
    religion:"Judaïsme 73%, Islam 18%, Christianisme 2%, Druze 2%",
    geo:"Plaine côtière méditerranéenne fertile. Désert du Néguev (60% territoire). Hautes-terres Cisjordanie. Dépression Jordan (mer Morte, -430 m — plus bas point Terre). Mer Rouge (Eilat). Golan (occupé depuis 1967, annexé 1981).",
    ressources:["Gaz offshore (Léviathan, Tamar — 3e Méditerranée)","Potasse (mer Morte)","Technologies de pointe (cybersécurité, agritech, défense)","Eau recyclée (85% eaux usées réutilisées — modèle mondial)"],
    energie:"Gaz naturel désormais autosuffisant. Export vers Égypte et Jordanie. Centrale nucléaire Dimona (non confirmée officiellement — bombes nucléaires estimées 80-400). Solaire en développement.",
    economie:"PIB ~$525 Mds. High-tech : 50% exportations. Start-up Nation (~7 000 startups). PIB/hab ~$55 000. Coût guerre Gaza 2024 : ~$50 Mds. Pression économique croissante.",
    histoire:"Antiquité : royaumes d'Israël et Juda. Diaspora après destruction Temple (70 apr. J.-C.). Mouvement sioniste (Herzl, 1897). Déclaration Balfour 1917. Mandat britannique. Création État d'Israël 1948 (guerre indépendance / Nakba). Guerres 1948, 1956, 1967 (Six Jours — occupation Gaza, Cisjordanie, Golan, Sinaï), 1973 (Kippour). Paix Égypte 1979, Jordanie 1994. Oslo 1993-1995. 2e Intifada 2000. Gaza : retrait 2005, blocus 2007. Accords Abraham 2020.",
    politique:"Conflit Gaza depuis 7 octobre 2023 (attaque Hamas : 1 200 morts israéliens, 250 otages). Opération terrestre : +40 000 morts palestiniens (ONU, 2024). Tensions Liban (Hezbollah, op. septembre 2024). Frappes Iran (avril 2024, représailles). CIJ : procédure génocide (Afrique du Sud). Crise politique interne (réforme judiciaire). Colonisation Cisjordanie accélérée.",
    conflits:"Gaza (Hamas). Liban (Hezbollah). Iran (missiles/drones). Cisjordanie (colonisation, IDF, milices colons). Syrie (frappes préventives). Yémen (Houthis).",
    voisins:{
      "Palestine (Gaza)":"Frontière sud. Blocus. Conflit armé actif depuis oct. 2023.",
      "Palestine (CJ)":"Occupation militaire. Colonisation. Autorité Palestinienne.",
      "Liban":"Frontière nord. Hezbollah. Opération 2024 (décapitation état-major). FINUL.",
      "Syrie":"Frontière Golan. Frappes préventives dépôts armes. Chute Assad 2024.",
      "Jordanie":"Frontière est. Paix 1994. Coordination sécurité. Eau (accord).",
      "Égypte":"Frontière SO (Sinaï). Paix 1979. Coordination Gaza."
    }
  },

  // ── ASIE ─────────────────────────────────────────────────────
  "CHN": {
    nom:"Chine", capitale:"Pékin", pop:"1 408 M", superficie:"9 596 960 km²",
    regime:"République populaire — Parti communiste (Xi Jinping, secrétaire général et président à vie depuis 2018)",
    langue:"Mandarin (putonghua, officiel), cantonais, shanghaïen, tibétain, ouïghour, mongol (8 langues majeures + 300 dialectes)",
    religion:"Athéisme d'État. Bouddhisme 18%, taoïsme, confucianisme (pratiques traditionnelles). Islam ~2% (Ouïghours, Hui). Christianisme ~5%.",
    geo:"Diversité extrême : Tibesti (plateau 4 500 m moy.), Himalaya (8 849 m), déserts Gobi/Taklamakan, plaines fleuries (Yangtze, Huanghe), forêts sud-est, façade maritime 14 500 km. 14 voisins terrestres (record mondial). Mer de Chine du Sud/orientale.",
    ressources:["Charbon (1er producteur mondial)","Terres rares (60% production mondiale)","Or","Acier","Tungstène","Eau douce (déficit nord)","Lithium (Qinghai)"],
    energie:"1er consommateur et émetteur CO2. Charbon 55% mix. Mais 1er investisseur ENR (solaire, éolien). Nucléaire (55 réacteurs). Pétrole importé (Moyen-Orient, Russie, Afrique). Barrage Trois-Gorges (22 GW).",
    economie:"PIB ~$18 500 Mds (2e mondiale, 1ère PPP). Croissance ralentie (~5%). Crise immobilier (Evergrande). Exportations : 2 600 Mds$/an. BRI (Belt and Road Initiative) : 150 pays, 1 000 Mds$ engagés. Déflation 2024. Chômage jeunes 20%+.",
    histoire:"Civilisation 4 000 ans. Dynasties impériales (Han, Tang, Song, Ming, Qing). Guerres de l'Opium (1839, 1856). Chute Empire 1912. Guerre civile nationalistes/communistes. Fondation RPC 1949 (Mao). Grand Bond en Avant (1959-61, 30-55 M morts). Révolution Culturelle 1966-76. Deng Xiaoping : réformes économiques 1978. Tiananmen 1989. Montée en puissance 2000s.",
    politique:"Xi Jinping : concentration pouvoir unprecedented. Taiwan : réunification objectif déclaré (force si nécessaire). Xinjiang : internement Ouïghours (1 M+, ONU). Tibet : contrôle total. Hong Kong : érosion autonomie (loi sécurité 2020). Rivalité USA (trade war, tech war). SCO (Organisation de Coopération de Shanghai). BRICS. Accord 25 ans Iran. Médiation Arabie-Iran 2023.",
    conflits:"Taïwan (latent, risque guerre mondiale). Mer de Chine du Sud (Philippines, Vietnam). LAC Ladakh (Inde). Ouïghours (Xinjiang). Diaspora tibétaine. Rivalité USA–Chine globale.",
    voisins:{
      "Russie":"Frontière nord (4 300 km, la plus longue). Partenariat sans limites (2022). Convergence anti-USA mais méfiance historique.",
      "Inde":"Frontière Himalaya/LAC (3 488 km). Conflit Ladakh 2020. Rivalité stratégique Indo-Pacifique.",
      "Vietnam":"Frontière sud (1 297 km). Mer de Chine du Sud. Guerre 1979. Nationalisme vietnamien anti-chinois fort.",
      "Kazakhstan":"Frontière nord-ouest. OCS. BRI. Ressources.",
      "Pakistan":"Frontière nord-ouest. CPEC (60 Mds$). Alliance stratégique vs Inde.",
      "Afghanistan":"Frontière NO (Wakhan). Taliban : relations pragmatiques.",
      "Myanmar":"Frontière sud. BRI. Guerre civile : déstabilisation frontière.",
      "Corée du Nord":"Frontière nord-est (Tumen/Yalu). Parrainage stratégique. Nucléaire."
    }
  },

  "RUS": {
    nom:"Russie", capitale:"Moscou", pop:"143 M", superficie:"17 098 242 km²",
    regime:"Fédération autoritaire (Poutine — Président depuis 1999 quasi-ininterrompu)",
    langue:"Russe (officiel), tatar, bachkir, ukrainien, tchétchène (35 langues reconnues + 100 dialectes)",
    religion:"Orthodoxie 70%, Islam 10% (Tatarstan, Caucase, Bachkirie), bouddhisme (Bouriatie, Kalmoukie)",
    geo:"11 fuseaux horaires. Plaine d'Europe orientale. Oural (frontière Europe–Asie). Sibérie (permafrost, taïga). Extrême-Orient (Pacifique). Caucause du Nord (Tchétchénie). Mer Baltique, Noire, Caspienne, Arctique, Pacifique, Barents. 14 pays voisins.",
    ressources:["Pétrole (3e producteur mondial — 10,7 M b/j)","Gaz naturel (1er réserves mondiales — Gazprom)","Charbon","Or (2e mondial)","Diamants (1er mondial — Alrosa)","Nickel","Palladium (40% mondial)","Blé (1er exportateur)","Forêts (20% mondiales)"],
    energie:"Économie de rente hydrocarbures. 60% revenus fédéraux. Gazprom monopole gaz. Rosneft pétrole. Sanctions 2022 : pivot vers Asie (Chine, Inde). Cap prix G7 ($60). Pipeline Power of Siberia (Chine). GNL Yamal.",
    economie:"PIB ~$2 240 Mds (11e mondiale). Économie de guerre 2022-24 (industrie défense 6% PIB). Inflation 8%. Sanctions SWIFT exclues grandes banques. Ruble volatile. Chômage bas (main-d'œuvre mobilisée).",
    histoire:"Russie de Kiev 10e s. Invasion mongole 1237. Ivan le Terrible 1ère unification. Pierre le Grand (empire, 'fenêtre Europe'). Catherine II (expansion sud). Guerres napoléoniennes. Empire 19e s. (Caucase, Asie centrale). Révolution 1917. URSS. 2e Guerre mondiale (27 M morts). Guerre froide. Dissolution URSS 1991. Eltsine. Poutine.",
    politique:"Invasion Ukraine 24 fév. 2022 (guerre la plus grande en Europe depuis 1945). Annexion Crimée 2014. Syrie (depuis 2015). Wagner/Africa Corps (Sahel, Libye, Soudan). Doctrines Gerasimov (guerre hybride). Menace nucléaire tactique. OCS/BRICS. Relations 'partenariat sans limites' Chine.",
    conflits:"Ukraine (guerre conventionnelle majeure). Tchétchénie (stabilisée sous Kadyrov). Géorgie (2008). Syrie. Sahel/Afrique (proxy Wagner). Arctique (compétition ressources).",
    voisins:{
      "Ukraine":"Frontière SO (2 295 km). Guerre en cours depuis 2022.",
      "Biélorussie":"Frontière SO. Allié quasi-vassal. Déploiements militaires.",
      "Finlande":"Frontière nord (1 340 km). Nouveau membre OTAN 2023 : 1 300 km nouvelles frontières OTAN-Russie.",
      "Chine":"Frontière est (4 300 km). Partenariat stratégique.",
      "Kazakhstan":"Frontière sud (7 512 km, la + longue Russie). OCS, influence russe.",
      "Géorgie":"Frontière SO. Ossétie, Abkhazie occupées.",
      "Azerbaïdjan":"Frontière SO (Dagestan). Corridor de transit Caspienne."
    }
  },

  // ── EUROPE ────────────────────────────────────────────────────
  "UKR": {
    nom:"Ukraine", capitale:"Kiev", pop:"37 M (avant guerre : 44 M)", superficie:"603 550 km²",
    regime:"République présidentielle (Zelensky depuis 2019)",
    langue:"Ukrainien (officiel, dominant), russe (surtout est/sud avant guerre)",
    religion:"Orthodoxie (Église orthodoxe d'Ukraine 65%), grecque-catholique, catholique",
    geo:"Grande plaine d'Europe orientale. Steppe fertile ('Chernozem' — terres noires, parmi les meilleures au monde). Carpates (SO). Crimée (occupée). Accès mer Noire et mer d'Azov (partiellement bloqué). Dniepr (fleuve stratégique, ligne de défense).",
    ressources:["Fer (4e mondial)","Manganèse","Titane","Uranium","Charbon (Donbass — occupé)","Blé et maïs (grenier Europe)","Lithium","Terres rares"],
    energie:"Nucléaire (15 réacteurs, 50% électricité). Centrale Zaporijjia (+ grande Europe, occupée Russie). Dépendance gaz russe historique → sevrage 2022. Transit gaz russe vers Europe (terminé jan. 2025). Éolien et solaire en croissance.",
    economie:"PIB ~$160 Mds (avant guerre ~$200 Mds). Perte ~40% PIB 2022. Aide internationale ~100 Mds$/an (USA, UE, OTAN). Reconstruction estimée ~500 Mds$. Blé/maïs : exports bloqués (accord céréalier mer Noire, fragile).",
    histoire:"Rus de Kiev 9e s. (berceau civilisation slave). Mongols 13e s. Commonwealth polono-lituanien. Empire russe. URSS (Holodomor 1932-33 : 3-7 M morts). Allemagne nazie 1941-44. URSS jusqu'en 1991. Indépendance 1991. Orange 2004. Maïdan 2014. Crimée annexée 2014. Donbass (guerre 2014). Invasion totale fév. 2022.",
    politique:"Candidature UE (accordée 2022, négociations). Candidature OTAN (bloquée en attendant fin guerre). Aide militaire massive Occident. Appels gel conflit ou négociations (pression USA Trump 2025). Mobilisation totale. Pertes importantes (chiffres classifiés).",
    conflits:"Guerre Russie (2022–en cours). Front ~900 km. Frappes drones/missiles sur infrastructures. Zaporijjia : risque nucléaire.",
    voisins:{
      "Russie":"Frontière NE et E. Agresseur. Front de guerre.",
      "Biélorussie":"Frontière nord. Utilisée comme plateforme d'attaque. Lukachenko allié Poutine.",
      "Pologne":"Frontière ouest. Membre OTAN. 1er hub aide militaire Ukraine (Rzeszów). Accueil 1 M réfugiés.",
      "Roumanie":"Frontière SO. OTAN. Transit armes. Base OTAN Mihail Kogalniceanu.",
      "Hongrie":"Frontière SO. Orban : frein aide militaire UE/OTAN. Relations complexes.",
      "Slovaquie":"Frontière SO. Fico : positions ambiguës.",
      "Moldavie":"Frontière SO. Transnistrie (russe). Déstabilisation crainte."
    }
  },

  // ── AMÉRIQUES ────────────────────────────────────────────────
  "USA": {
    nom:"États-Unis d'Amérique", capitale:"Washington D.C.", pop:"335 M", superficie:"9 833 517 km²",
    regime:"République fédérale (Trump, 47e président depuis jan. 2025)",
    langue:"Anglais (de facto officiel), espagnol (50 M locuteurs), français (Louisiane), amérindien",
    religion:"Protestantisme 43%, catholicisme 20%, évangéliques 25%, non-affiliés 26%",
    geo:"Plaines centrales (Grandes Plaines). Rocheuses (ouest). Appalachians (est). Côtes Atlantique et Pacifique. Alaska (nord). Hawaï (Pacifique). Façade Golfe du Mexique. Grands Lacs (nord).",
    ressources:["Pétrole et gaz de schiste (1er producteur mondial — 13,3 M b/j)","Charbon","Maïs et soja (1ers mondiaux)","Cuivre","Or","Terres rares (en développement)","Eau douce"],
    energie:"Révolution du schiste (2010s) → 1er producteur pétrole et gaz mondial. Indépendance énergétique. IRA 2022 : 369 Mds$ ENR. Nucléaire 20% électricité. Exportateur GNL vers Europe.",
    economie:"PIB ~$27 800 Mds (1ère mondiale). Dollar : monnaie de réserve mondiale. Wall Street. Tech (Silicon Valley). Déficit commercial. Dettes $33 000 Mds. Tarifs douaniers Trump 2025 (60% Chine, 10–20% reste). Inflation revenue ~3%.",
    histoire:"Colonisation européenne 16e-18e s. Indépendance 1776. Guerre civile 1861-65. 1ère/2e guerres mondiales. Guerre froide (plan Marshall, OTAN, endiguement). Vietnam. Chute URSS 1991. 11 sept. 2001. Irak/Afghanistan. Crise 2008. Trump (2017-21, 2025-).",
    politique:"Trump 2025 : America First, tarifs, réduction aide Ukraine, retrait OMS, tensions OTAN. Rivalité Chine (semiconducteurs, TikTok, BRI vs PGII). Soutien Israël (mais pression cessez-le-feu). AUKUS (Australie, UK). QUAD (Japon, Inde, Australie). 800+ bases militaires mondiales.",
    conflits:"Ukraine (soutien militaire ~75 Mds$, sous pression Trump). Israël–Gaza. Indo-Pacifique (Taïwan). Sahel (recul). Yémen (opérations anti-Houthis). Iran (sanctions, risque conflit).",
    voisins:{
      "Canada":"Frontière nord (8 891 km). USMCA. NORAD. OTAN. Trump : menaces annexion/51e État.",
      "Mexique":"Frontière sud (3 145 km). USMCA. Migration. Cartels. Mur.",
      "Cuba":"Mer des Caraïbes. Embargo 60 ans. Base Guantanamo.",
      "Bahamas":"Mer des Caraïbes. Relations cordiales."
    }
  },

  // ── AFRIQUE AUSTRALE ─────────────────────────────────────────
  "ZAF": {
    nom:"Afrique du Sud", capitale:"Pretoria / Le Cap / Bloemfontein", pop:"62 M", superficie:"1 221 037 km²",
    regime:"République (ANC, Ramaphosa — gouvernement coalition ANC-DA depuis 2024)",
    langue:"11 langues officielles (zoulou, xhosa, afrikaans, anglais, sotho, tswana, venda, tsonga, swati, ndébélé, pedi)",
    religion:"Christianisme 86%, Islam 2%, hindouisme 1%",
    geo:"Plateau intérieur (veld). Drakensberg (est, 3 482 m). Cap de Bonne-Espérance (convergence océans). Désert du Karoo (centre). Kalahari (nord-ouest). Côtes Atlantique et Indien (2 800 km total).",
    ressources:["Or (4e mondial)","Platine (75% réserves mondiales)","Chrome (45% mondial)","Manganèse","Charbon","Diamants","Titane","Vanadium"],
    energie:"Charbon 85% électricité (Eskom — en crise, délestages 12h/j 2022-23). Centrale nucléaire Koeberg. Transition ENR en cours (IRP 2019). Dépendance charbon malgré objectifs climat.",
    economie:"PIB ~$400 Mds (2e Afrique après Nigeria). Chômage 32%. Inégalités extrêmes (Gini 0,63 — plus élevé au monde). Corruption. Infrastructure dégradée. BRICS membre fondateur.",
    histoire:"Peuples San, Khoikhoi, Bantous. Colonisation hollandaise (Boers) 1652. Colonisation britannique 19e s. Guerres anglo-boers. Union 1910. Apartheid 1948-1994. Mandela, FNL, Nobels. Transition pacifique 1994. ANC au pouvoir depuis. Corruption 'État capturé' Zuma.",
    politique:"BRICS : présidence 2023 (Johannesburg — expansion BRICS+). CIJ : procédure génocide vs Israël (jan. 2024). Relations Russie : abstention ONU Crimée. Géopolitique équidistante ('non-alignement actif'). Crise énergétique Eskom. Crime organisé élevé.",
    conflits:"Conflits frontaliers faibles. Crime élevé intérieur. Tensions xénophobes (migrants zimbabwéens, mozambicains).",
    voisins:{
      "Mozambique":"Frontière est. MOZAL (aluminium). Insurgence islamiste Cabo Delgado (Total GNL, SADC-MI).",
      "Zimbabwe":"Frontière nord. Crise économique. Millions Zimbabwéens en Afrique du Sud.",
      "Botswana":"Frontière NO. Diamants (De Beers). Stabilité.",
      "Namibie":"Frontière ouest. Ex-Afrique du Sud (indépendance 1990). Uranium.",
      "Lesotho":"Enclave. Eau (projet LHWP). Dépendance totale.",
      "Eswatini":"Enclave. Monarchie absolue. Commerce."
    }
  },
};

// ── LABELS PAYS (en français) ─────────────────────────────────────
// tier: 1=majeur (zoom≥2), 2=standard (zoom≥3), 3=petit (zoom≥4)
const PAYS_LABELS = [
  // Afrique du Nord / Maghreb
  { nom:"Algérie",     lat:28,    lon:3,     tier:2 },
  { nom:"Maroc",       lat:32,    lon:-6,    tier:2 },
  { nom:"Tunisie",     lat:34,    lon:9,     tier:3 },
  { nom:"Libye",       lat:27,    lon:17,    tier:2 },
  { nom:"Égypte",      lat:27,    lon:30,    tier:1 },
  // Sahel / Afrique de l'Ouest
  { nom:"Mauritanie",  lat:20,    lon:-10,   tier:2 },
  { nom:"Mali",        lat:17,    lon:-4,    tier:2 },
  { nom:"Niger",       lat:17,    lon:8,     tier:2 },
  { nom:"Tchad",       lat:15,    lon:19,    tier:2 },
  { nom:"Sénégal",     lat:14,    lon:-15,   tier:3 },
  { nom:"Gambie",      lat:13.4,  lon:-15.5, tier:3 },
  { nom:"Guinée",      lat:10,    lon:-11,   tier:3 },
  { nom:"Guinée-Bissau",lat:12,   lon:-15,   tier:3 },
  { nom:"Sierra Leone",lat:8,     lon:-12,   tier:3 },
  { nom:"Libéria",     lat:6,     lon:-9,    tier:3 },
  { nom:"Côte d'Ivoire",lat:8,    lon:-5,    tier:2 },
  { nom:"Burkina Faso",lat:13,    lon:-2,    tier:2 },
  { nom:"Ghana",       lat:8,     lon:-1,    tier:3 },
  { nom:"Togo",        lat:8,     lon:1,     tier:3 },
  { nom:"Bénin",       lat:9,     lon:2,     tier:3 },
  { nom:"Nigeria",     lat:10,    lon:8,     tier:1 },
  // Afrique centrale
  { nom:"Cameroun",    lat:6,     lon:12,    tier:2 },
  { nom:"Centrafrique",lat:7,     lon:21,    tier:2 },
  { nom:"Gabon",       lat:-1,    lon:12,    tier:3 },
  { nom:"Congo",       lat:-1,    lon:15,    tier:3 },
  { nom:"RDC",         lat:-3,    lon:23,    tier:1 },
  { nom:"Guinée Équat.",lat:1.5,  lon:10,    tier:3 },
  // Afrique de l'Est / Corne
  { nom:"Soudan",      lat:16,    lon:30,    tier:2 },
  { nom:"Soudan du Sud",lat:7,    lon:30,    tier:2 },
  { nom:"Éthiopie",    lat:9,     lon:40,    tier:2 },
  { nom:"Érythrée",    lat:15,    lon:39,    tier:3 },
  { nom:"Djibouti",    lat:12,    lon:43,    tier:3 },
  { nom:"Somalie",     lat:6,     lon:47,    tier:2 },
  { nom:"Kenya",       lat:0,     lon:38,    tier:2 },
  { nom:"Ouganda",     lat:1,     lon:32,    tier:3 },
  { nom:"Rwanda",      lat:-2,    lon:30,    tier:3 },
  { nom:"Burundi",     lat:-3,    lon:30,    tier:3 },
  { nom:"Tanzanie",    lat:-6,    lon:35,    tier:2 },
  // Afrique australe
  { nom:"Angola",      lat:-12,   lon:18,    tier:2 },
  { nom:"Zambie",      lat:-14,   lon:27,    tier:3 },
  { nom:"Malawi",      lat:-13,   lon:34,    tier:3 },
  { nom:"Mozambique",  lat:-18,   lon:35,    tier:2 },
  { nom:"Zimbabwe",    lat:-19,   lon:30,    tier:3 },
  { nom:"Botswana",    lat:-22,   lon:24,    tier:3 },
  { nom:"Namibie",     lat:-22,   lon:17,    tier:3 },
  { nom:"Afrique du Sud",lat:-29, lon:24,    tier:1 },
  { nom:"Lesotho",     lat:-29.5, lon:28.5,  tier:3 },
  { nom:"Eswatini",    lat:-26.5, lon:31.5,  tier:3 },
  { nom:"Madagascar",  lat:-19,   lon:47,    tier:2 },

  // Moyen-Orient
  { nom:"Turquie",     lat:39,    lon:35,    tier:1 },
  { nom:"Syrie",       lat:35,    lon:38,    tier:2 },
  { nom:"Liban",       lat:34,    lon:36,    tier:3 },
  { nom:"Israël",      lat:31,    lon:35,    tier:2 },
  { nom:"Jordanie",    lat:31,    lon:37,    tier:3 },
  { nom:"Irak",        lat:33,    lon:44,    tier:2 },
  { nom:"Iran",        lat:32,    lon:53,    tier:1 },
  { nom:"Arabie Saoudite",lat:24, lon:45,    tier:1 },
  { nom:"Yémen",       lat:16,    lon:48,    tier:2 },
  { nom:"Oman",        lat:21,    lon:57,    tier:3 },
  { nom:"Émirats A.U.",lat:24,    lon:54,    tier:3 },
  { nom:"Qatar",       lat:25.3,  lon:51.2,  tier:3 },
  { nom:"Koweït",      lat:29.3,  lon:47.5,  tier:3 },

  // Asie
  { nom:"Afghanistan", lat:33,    lon:65,    tier:2 },
  { nom:"Pakistan",    lat:30,    lon:70,    tier:1 },
  { nom:"Inde",        lat:21,    lon:79,    tier:1 },
  { nom:"Bangladesh",  lat:24,    lon:90,    tier:2 },
  { nom:"Népal",       lat:28,    lon:84,    tier:3 },
  { nom:"Bhoutan",     lat:27.5,  lon:90.5,  tier:3 },
  { nom:"Sri Lanka",   lat:7.5,   lon:81,    tier:3 },
  { nom:"Myanmar",     lat:22,    lon:96,    tier:2 },
  { nom:"Thaïlande",   lat:15,    lon:101,   tier:2 },
  { nom:"Laos",        lat:18,    lon:104,   tier:3 },
  { nom:"Cambodge",    lat:13,    lon:105,   tier:3 },
  { nom:"Vietnam",     lat:16,    lon:108,   tier:2 },
  { nom:"Malaisie",    lat:4,     lon:110,   tier:2 },
  { nom:"Indonésie",   lat:-3,    lon:115,   tier:1 },
  { nom:"Philippines", lat:13,    lon:122,   tier:1 },
  { nom:"Chine",       lat:35,    lon:103,   tier:1 },
  { nom:"Mongolie",    lat:47,    lon:103,   tier:2 },
  { nom:"Corée du Nord",lat:40,   lon:127,   tier:2 },
  { nom:"Corée du Sud",lat:36,    lon:128,   tier:2 },
  { nom:"Japon",       lat:36,    lon:138,   tier:1 },
  { nom:"Taïwan",      lat:23.5,  lon:121,   tier:2 },
  // Asie centrale / Caucase
  { nom:"Kazakhstan",  lat:48,    lon:68,    tier:1 },
  { nom:"Ouzbékistan", lat:41,    lon:64,    tier:2 },
  { nom:"Turkménistan",lat:39,    lon:59,    tier:3 },
  { nom:"Kirghizstan", lat:41,    lon:74,    tier:3 },
  { nom:"Tadjikistan", lat:39,    lon:71,    tier:3 },
  { nom:"Géorgie",     lat:42,    lon:43,    tier:3 },
  { nom:"Arménie",     lat:40,    lon:45,    tier:3 },
  { nom:"Azerbaïdjan", lat:40,    lon:48,    tier:3 },

  // Europe de l'Est
  { nom:"Russie",      lat:60,    lon:90,    tier:1 },
  { nom:"Ukraine",     lat:49,    lon:32,    tier:1 },
  { nom:"Biélorussie", lat:53,    lon:28,    tier:2 },
  { nom:"Moldavie",    lat:47,    lon:29,    tier:3 },
  // Balkans
  { nom:"Roumanie",    lat:46,    lon:25,    tier:2 },
  { nom:"Bulgarie",    lat:43,    lon:25,    tier:3 },
  { nom:"Grèce",       lat:39,    lon:22,    tier:2 },
  { nom:"Albanie",     lat:41,    lon:20,    tier:3 },
  { nom:"Macédoine N.",lat:41.6,  lon:21.7,  tier:3 },
  { nom:"Kosovo",      lat:42.6,  lon:20.9,  tier:3 },
  { nom:"Serbie",      lat:44,    lon:21,    tier:2 },
  { nom:"Monténégro",  lat:42.8,  lon:19.3,  tier:3 },
  { nom:"Bosnie",      lat:44,    lon:18,    tier:3 },
  { nom:"Croatie",     lat:45.5,  lon:16,    tier:3 },
  { nom:"Slovénie",    lat:46,    lon:15,    tier:3 },
  // Europe centrale
  { nom:"Hongrie",     lat:47,    lon:19,    tier:3 },
  { nom:"Slovaquie",   lat:49,    lon:19.5,  tier:3 },
  { nom:"Tchéquie",    lat:50,    lon:15,    tier:3 },
  { nom:"Pologne",     lat:52,    lon:19,    tier:1 },
  { nom:"Autriche",    lat:47.5,  lon:14,    tier:3 },
  { nom:"Suisse",      lat:46.8,  lon:8.2,   tier:3 },
  { nom:"Allemagne",   lat:51,    lon:10,    tier:1 },
  // Europe de l'Ouest
  { nom:"France",      lat:47,    lon:2,     tier:1 },
  { nom:"Italie",      lat:43,    lon:12,    tier:1 },
  { nom:"Espagne",     lat:40,    lon:-4,    tier:1 },
  { nom:"Portugal",    lat:39,    lon:-8,    tier:2 },
  { nom:"Belgique",    lat:50.8,  lon:4.5,   tier:3 },
  { nom:"Pays-Bas",    lat:52.5,  lon:5.5,   tier:3 },
  { nom:"Royaume-Uni", lat:54,    lon:-2,    tier:1 },
  { nom:"Irlande",     lat:53.5,  lon:-8,    tier:3 },
  // Europe du Nord
  { nom:"Danemark",    lat:56,    lon:10,    tier:3 },
  { nom:"Suède",       lat:62,    lon:15,    tier:2 },
  { nom:"Norvège",     lat:64,    lon:12,    tier:2 },
  { nom:"Finlande",    lat:64,    lon:26,    tier:2 },
  { nom:"Estonie",     lat:59,    lon:25.5,  tier:3 },
  { nom:"Lettonie",    lat:57,    lon:25,    tier:3 },
  { nom:"Lituanie",    lat:55.5,  lon:24,    tier:3 },
  { nom:"Islande",     lat:64.5,  lon:-19,   tier:2 },

  // Amérique du Nord
  { nom:"États-Unis",  lat:39,    lon:-99,   tier:1 },
  { nom:"Canada",      lat:60,    lon:-105,  tier:1 },
  { nom:"Mexique",     lat:23,    lon:-102,  tier:1 },
  // Amérique centrale / Caraïbes
  { nom:"Cuba",        lat:22,    lon:-79,   tier:2 },
  { nom:"Haïti",       lat:19,    lon:-72,   tier:3 },
  { nom:"Rép. Dom.",   lat:19,    lon:-70,   tier:3 },
  { nom:"Jamaïque",    lat:18,    lon:-77,   tier:3 },
  { nom:"Guatemala",   lat:15.5,  lon:-90.5, tier:3 },
  { nom:"Honduras",    lat:15,    lon:-86.5, tier:3 },
  { nom:"Nicaragua",   lat:13,    lon:-85,   tier:3 },
  { nom:"Costa Rica",  lat:10,    lon:-84,   tier:3 },
  { nom:"Panama",      lat:9,     lon:-80,   tier:3 },
  { nom:"Salvador",    lat:13.7,  lon:-88.9, tier:3 },
  { nom:"Belize",      lat:17.2,  lon:-88.5, tier:3 },
  // Amérique du Sud
  { nom:"Colombie",    lat:4,     lon:-72,   tier:2 },
  { nom:"Venezuela",   lat:8,     lon:-66,   tier:2 },
  { nom:"Guyana",      lat:5,     lon:-58,   tier:3 },
  { nom:"Suriname",    lat:4,     lon:-56,   tier:3 },
  { nom:"Brésil",      lat:-10,   lon:-55,   tier:1 },
  { nom:"Pérou",       lat:-9,    lon:-75,   tier:2 },
  { nom:"Bolivie",     lat:-16,   lon:-65,   tier:2 },
  { nom:"Équateur",    lat:-1,    lon:-78,   tier:3 },
  { nom:"Argentine",   lat:-38,   lon:-65,   tier:1 },
  { nom:"Chili",       lat:-35,   lon:-71,   tier:2 },
  { nom:"Uruguay",     lat:-33,   lon:-56,   tier:3 },
  { nom:"Paraguay",    lat:-23,   lon:-58,   tier:3 },

  // Océanie
  { nom:"Australie",   lat:-25,   lon:135,   tier:1 },
  { nom:"Nouvelle-Zélande",lat:-41,lon:174,  tier:2 },
  { nom:"Papouasie-N.G.",lat:-6,  lon:144,   tier:3 },
];

// Exporter toutes les données
if (typeof window !== 'undefined') {
  window.GEO = { MERS, FLEUVES, DETROITS, MONTAGNES, TERRITOIRES, VILLES, PAYS_DATA, PAYS_LABELS };
}
